import { POKEMON } from './PokemonRates';

export const ROOM_VARIABLES = {
  smax: 3,
  mmax: 3,
  lmax: 3,
  llmax: 0,
};

export const ROOM_2 = {
  DIAMOND: [
    { zukanflag: 6, ...POKEMON.Caterpie },
    { zukanflag: 6, ...POKEMON.Rattata },
    { zukanflag: 6, ...POKEMON.Raticate },
    { zukanflag: 1, ...POKEMON.Zubat },
    { zukanflag: 2, ...POKEMON.Golbat },
    { zukanflag: 6, ...POKEMON.Oddish },
    { zukanflag: 6, ...POKEMON.Gloom },
    { zukanflag: 6, ...POKEMON.Venonat },
    { zukanflag: 6, ...POKEMON.Venomoth },
    { zukanflag: 1, ...POKEMON.Psyduck },
    { zukanflag: 6, ...POKEMON.Mankey },
    { zukanflag: 6, ...POKEMON.Primeape },
    { zukanflag: 6, ...POKEMON.Growlithe },
    { zukanflag: 1, ...POKEMON.Machop },
    { zukanflag: 3, ...POKEMON.Machoke },
    { zukanflag: 1, ...POKEMON.Geodude },
    { zukanflag: 3, ...POKEMON.Graveler },
    { zukanflag: 6, ...POKEMON.Magnemite },
    { zukanflag: 6, ...POKEMON.Farfetchd },
    { zukanflag: 6, ...POKEMON.Doduo },
    { zukanflag: 6, ...POKEMON.Krabby },
    { zukanflag: 6, ...POKEMON.Voltorb },
    { zukanflag: 6, ...POKEMON.Lickitung },
    { zukanflag: 6, ...POKEMON.Rhyhorn },
    { zukanflag: 6, ...POKEMON.Rhydon },
    { zukanflag: 6, ...POKEMON.Tauros },
    { zukanflag: 6, ...POKEMON.Sentret },
    { zukanflag: 6, ...POKEMON.Furret },
    { zukanflag: 2, ...POKEMON.Hoothoot },
    { zukanflag: 6, ...POKEMON.Natu },
    { zukanflag: 3, ...POKEMON.Aipom },
    { zukanflag: 1, ...POKEMON.Murkrow },
    { zukanflag: 6, ...POKEMON.Houndoom },
    { zukanflag: 6, ...POKEMON.Tyrogue },
    { zukanflag: 6, ...POKEMON.Miltank },
    { zukanflag: 6, ...POKEMON.Poochyena },
    { zukanflag: 6, ...POKEMON.Mightyena },
    { zukanflag: 6, ...POKEMON.Zigzagoon },
    { zukanflag: 3, ...POKEMON.Wingull },
    { zukanflag: 4, ...POKEMON.Pelipper },
    { zukanflag: 6, ...POKEMON.Skitty },
    { zukanflag: 6, ...POKEMON.Swablu },
    { zukanflag: 6, ...POKEMON.Corphish },
    { zukanflag: 6, ...POKEMON.Crawdaunt },
    { zukanflag: 6, ...POKEMON.Absol },
    { zukanflag: 1, ...POKEMON.Bidoof },
    { zukanflag: 2, ...POKEMON.Bibarel },
    { zukanflag: 1, ...POKEMON.Kricketot },
    { zukanflag: 1, ...POKEMON.Shinx },
    { zukanflag: 4, ...POKEMON.Luxio },
    { zukanflag: 1, ...POKEMON.Budew },
    { zukanflag: 1, ...POKEMON.Pachirisu },
    { zukanflag: 1, ...POKEMON.Buneary },
    { zukanflag: 2, ...POKEMON.Chingling },
    { zukanflag: 2, ...POKEMON.Stunky },
    { zukanflag: 2, ...POKEMON.Skuntank },
    { zukanflag: 3, ...POKEMON.Munchlax },
    { zukanflag: 5, ...POKEMON.Mantyke },
  ],
  PEARL: [
    { zukanflag: 6, ...POKEMON.Weedle },
    { zukanflag: 6, ...POKEMON.Rattata },
    { zukanflag: 6, ...POKEMON.Raticate },
    { zukanflag: 6, ...POKEMON.Sandshrew },
    { zukanflag: 6, ...POKEMON.Sandslash },
    { zukanflag: 6, ...POKEMON.Vulpix },
    { zukanflag: 1, ...POKEMON.Zubat },
    { zukanflag: 2, ...POKEMON.Golbat },
    { zukanflag: 6, ...POKEMON.Oddish },
    { zukanflag: 6, ...POKEMON.Gloom },
    { zukanflag: 6, ...POKEMON.Venonat },
    { zukanflag: 6, ...POKEMON.Venomoth },
    { zukanflag: 1, ...POKEMON.Psyduck },
    { zukanflag: 6, ...POKEMON.Mankey },
    { zukanflag: 6, ...POKEMON.Primeape },
    { zukanflag: 1, ...POKEMON.Machop },
    { zukanflag: 3, ...POKEMON.Machoke },
    { zukanflag: 1, ...POKEMON.Geodude },
    { zukanflag: 3, ...POKEMON.Graveler },
    { zukanflag: 6, ...POKEMON.Slowpoke },
    { zukanflag: 6, ...POKEMON.Magnemite },
    { zukanflag: 6, ...POKEMON.Farfetchd },
    { zukanflag: 6, ...POKEMON.Doduo },
    { zukanflag: 6, ...POKEMON.Krabby },
    { zukanflag: 6, ...POKEMON.Voltorb },
    { zukanflag: 6, ...POKEMON.Lickitung },
    { zukanflag: 6, ...POKEMON.Rhyhorn },
    { zukanflag: 6, ...POKEMON.Rhydon },
    { zukanflag: 6, ...POKEMON.Tauros },
    { zukanflag: 6, ...POKEMON.Sentret },
    { zukanflag: 6, ...POKEMON.Furret },
    { zukanflag: 2, ...POKEMON.Hoothoot },
    { zukanflag: 6, ...POKEMON.Natu },
    { zukanflag: 3, ...POKEMON.Aipom },
    { zukanflag: 6, ...POKEMON.Teddiursa },
    { zukanflag: 6, ...POKEMON.Houndoom },
    { zukanflag: 6, ...POKEMON.Tyrogue },
    { zukanflag: 6, ...POKEMON.Miltank },
    { zukanflag: 6, ...POKEMON.Poochyena },
    { zukanflag: 6, ...POKEMON.Mightyena },
    { zukanflag: 6, ...POKEMON.Zigzagoon },
    { zukanflag: 3, ...POKEMON.Wingull },
    { zukanflag: 4, ...POKEMON.Pelipper },
    { zukanflag: 6, ...POKEMON.Skitty },
    { zukanflag: 6, ...POKEMON.Swablu },
    { zukanflag: 6, ...POKEMON.Corphish },
    { zukanflag: 6, ...POKEMON.Crawdaunt },
    { zukanflag: 6, ...POKEMON.Absol },
    { zukanflag: 6, ...POKEMON.Bagon },
    { zukanflag: 6, ...POKEMON.Shelgon },
    { zukanflag: 1, ...POKEMON.Bidoof },
    { zukanflag: 2, ...POKEMON.Bibarel },
    { zukanflag: 1, ...POKEMON.Kricketot },
    { zukanflag: 1, ...POKEMON.Shinx },
    { zukanflag: 4, ...POKEMON.Luxio },
    { zukanflag: 1, ...POKEMON.Budew },
    { zukanflag: 1, ...POKEMON.Pachirisu },
    { zukanflag: 1, ...POKEMON.Buneary },
    { zukanflag: 4, ...POKEMON.Glameow },
    { zukanflag: 3, ...POKEMON.Purugly },
    { zukanflag: 2, ...POKEMON.Chingling },
    { zukanflag: 3, ...POKEMON.Munchlax },
    { zukanflag: 5, ...POKEMON.Mantyke },
  ],
};
