import { SPECIES } from './species';
import { GENDER_RATIOS } from './gender';

export const RNG_CONFIG = {
  [SPECIES.None]: {
    gender_ratio: 0,
    set_ivs: false,
    ability_filter: 3,
    is_roamer: false,
  },
  [SPECIES.Turtwig]: {
    gender_ratio: GENDER_RATIOS['87.5% ♂ / 12.5% ♀'],
    set_ivs: false,
    ability_filter: 3,
    delay: 64,
    is_roamer: false,
  },
  [SPECIES.Chimchar]: {
    gender_ratio: GENDER_RATIOS['87.5% ♂ / 12.5% ♀'],
    set_ivs: false,
    ability_filter: 3,
    delay: 64,
    is_roamer: false,
  },
  [SPECIES.Piplup]: {
    gender_ratio: GENDER_RATIOS['87.5% ♂ / 12.5% ♀'],
    set_ivs: false,
    ability_filter: 3,
    delay: 64,
    is_roamer: false,
  },
  [SPECIES.Eevee]: {
    gender_ratio: GENDER_RATIOS['87.5% ♂ / 12.5% ♀'],
    set_ivs: false,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Happiny]: {
    gender_ratio: GENDER_RATIOS['100% ♀'],
    set_ivs: false,
    ability_filter: 3,
    delay: 64,
    is_roamer: false,
  },
  [SPECIES.Riolu]: {
    gender_ratio: GENDER_RATIOS['87.5% ♂ / 12.5% ♀'],
    set_ivs: false,
    ability_filter: 3,
    delay: 64,
    is_roamer: false,
  },
  [SPECIES.Mew]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    shiny_filter: 4,
    ability_filter: 1,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Jirachi]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    shiny_filter: 4,
    ability_filter: 1,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Omanyte]: {
    gender_ratio: GENDER_RATIOS['87.5% ♂ / 12.5% ♀'],
    set_ivs: true,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Kabuto]: {
    gender_ratio: GENDER_RATIOS['87.5% ♂ / 12.5% ♀'],
    set_ivs: true,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Aerodactyl]: {
    gender_ratio: GENDER_RATIOS['87.5% ♂ / 12.5% ♀'],
    set_ivs: true,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Lileep]: {
    gender_ratio: GENDER_RATIOS['87.5% ♂ / 12.5% ♀'],
    set_ivs: true,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Anorith]: {
    gender_ratio: GENDER_RATIOS['87.5% ♂ / 12.5% ♀'],
    set_ivs: true,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Cranidos]: {
    gender_ratio: GENDER_RATIOS['87.5% ♂ / 12.5% ♀'],
    set_ivs: true,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Shieldon]: {
    gender_ratio: GENDER_RATIOS['87.5% ♂ / 12.5% ♀'],
    set_ivs: true,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Drifloon]: {
    gender_ratio: GENDER_RATIOS['50% ♂ / 50% ♀'],
    set_ivs: false,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Spiritomb]: {
    gender_ratio: GENDER_RATIOS['50% ♂ / 50% ♀'],
    set_ivs: false,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Rotom]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: false,
    ability_filter: 3,
    delay: 90,
    is_roamer: false,
  },
  [SPECIES.Mesprit]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: true,
  },
  [SPECIES.Cresselia]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 104,
    is_roamer: true,
  },
  [SPECIES.Uxie]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Azelf]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Dialga]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Palkia]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Heatran]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Regigigas]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Giratina]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Articuno]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Zapdos]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Moltres]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Raikou]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Entei]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Suicune]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Regirock]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Regice]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Registeel]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Latias]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Latios]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Mewtwo]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Lugia]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.HoOh]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Kyogre]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Groudon]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Rayquaza]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 84,
    is_roamer: false,
  },
  [SPECIES.Darkrai]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Shaymin]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
  [SPECIES.Arceus]: {
    gender_ratio: GENDER_RATIOS['Genderless'],
    set_ivs: true,
    ability_filter: 3,
    delay: 0,
    is_roamer: false,
  },
};
